### ISSUE TITLE
got `_enforce_label_connectivity_cython() got an unexpected keyword argument 'start_label'`

### ISSUE THREAD

**Issue by chocoford** [rosalindfranklininstitute/cuda-slic#1]
## Reproduce
```python
import os
import numpy as np
from PIL import Image

from cuda_slic import slic
data_dir = ...
img_name = ...
n_segments = 500
img = np.array(Image.open(os.path.join(data_dir, img_name + '.jpg')))
segments = slic(img, n_segments=n_segments)

```

**Comment by markbasham** [comment]
Thanks for the bug report, I will have a go at fixing this, but our main developer is on holiday right now.  I think this might be to do with needing the very latest version of scipy of skimage, I cant remember which, as we use a bit of their code for one of the steps, and it was only introduced recently.

**Comment by chocoford** [comment]
@markbasham Thanks for replying. And it has been solved by just update `scikit`.

**Comment by markbasham** [comment]
Perfect, Glad that helped, hoped it was something like that :)  Please just let us know if you have any other issues, and ill close this ticket for now.
